[project]
name = "omnicopy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.120.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
